SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
INNER JOIN FOOD_ORDER FO
  ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022
AND MONTH(PRODUCE_DATE) = 5
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;